version: '3'

services:
  postgres_mice_lifespan:
    image: postgres
    user: ${MICE_LIFESPAN_UID}
    environment: # Set up postgres database name and password
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mice_lifespan
      POSTGRES_USER: admin
    ports: # Set up ports exposed for other containers to connect to
      - 5434:5432
    networks:
      - postgres_mice_lifespan_net
    volumes:
      - ./../mice_lifespan-postgres:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

  api:
    user: ${MICE_LIFESPAN_UID}
    build:
      context: .
      dockerfile: Dockerfile
    image: mice_lifespan-backend-dev
    hostname: mice_lifespan-api
    container_name: mice_lifespan-api-dev
    ports: # Set up ports exposed for other containers to connect to
      - 8088:8088
    volumes:
      - "./api:/api"
      - "./parsers:/parsers"
      - "./.env:/.env"
      - "./requirements.txt:/requirements.txt"
    depends_on:
      - postgres_mice_lifespan
    networks:
      - postgres_mice_lifespan_net
    expose:
      - 8088
networks:
  postgres_mice_lifespan_net:
    external:
      name: postgres_mice_lifespan_net
  default:
    external: false

