-- active substance
CREATE TABLE active_substance
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- time unit
CREATE TABLE time_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- intervention_period_reference_point
CREATE TABLE intervention_period_reference_point
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- intervention_type
CREATE TABLE intervention_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- journal
CREATE TABLE journal
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    link TEXT,
    rank TEXT
);

-- metabolic_enzyme
CREATE TABLE metabolic_enzyme
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- species
CREATE TABLE species
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- sex
CREATE TABLE sex
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- nutrition
CREATE TABLE nutrition
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- organisms_density
CREATE TABLE organisms_density
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number    INTEGER NOT NULL,
    area      NUMERIC,
    area_unit TEXT,
    constancy boolean
);

-- dosage_unit
CREATE TABLE dosage_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- drug_target
CREATE TABLE drug_target
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- experiment_site
CREATE TABLE experiment_site
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT
);

-- strain
CREATE TABLE strain
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    species_id INTEGER NOT NULL REFERENCES species (id) ON DELETE CASCADE
);

-- substance_delivery_way
CREATE TABLE substance_delivery_way
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- substance_delivery_frequency
CREATE TABLE substance_delivery_frequency
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- control_group
CREATE TABLE control_group
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description               TEXT,
    control_min_lifespan      NUMERIC,
    control_max_lifespan      NUMERIC,
    control_median_lifespan   NUMERIC,
    lifespan_unit_id          INTEGER REFERENCES time_unit (id) ON DELETE CASCADE,
    organisms_density_id      INTEGER REFERENCES organisms_density (id) ON DELETE CASCADE,
    survival_plot_source_link TEXT,
    survival_plot_coordinates jsonb,
    survival_raw_data         jsonb
);

-- publication
CREATE TABLE publication
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DOI"      TEXT,
    "PMID"     TEXT,
    date       date,
    journal_id INTEGER REFERENCES journal (id) ON DELETE CASCADE,
    authors    TEXT
);

-- experiment
CREATE TABLE experiment
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                            TEXT,
    publication_id                  INTEGER NOT NULL REFERENCES publication (id) ON DELETE CASCADE,
    species_id                      INTEGER NOT NULL REFERENCES species (id) ON DELETE CASCADE,
    control_group_id                INTEGER REFERENCES control_group (id) ON DELETE CASCADE,
    strain_id                       INTEGER REFERENCES strain (id) ON DELETE CASCADE,
    experiment_site_id              INTEGER REFERENCES experiment_site (id) ON DELETE CASCADE,
    result_change_max_lifespan      NUMERIC,
    result_change_median_lifespan   NUMERIC,
    sex_id                          INTEGER REFERENCES sex (id) ON DELETE CASCADE,
    -- temperature_conditions
    temperature_condition_range     numrange,
    temperature_condition_constance boolean,
    -- light_conditions
    light_condition_light_hours     NUMERIC,
    light_condition_dark_hours      NUMERIC,
    -- diet_condition
    diet_condition_feed_id          INTEGER,
    diet_condition_feed             TEXT,
    diet_condition_times_per_day    NUMERIC
);

-- treatment_group
CREATE TABLE treatment_group
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size                 INTEGER NOT NULL,
    survival_plot_data   jsonb,
    min_lifespan         NUMERIC,
    mean_lifespan        NUMERIC,
    median_lifespan      NUMERIC,
    max_lifespan         NUMERIC,
    lifespan_unit_id     INTEGER REFERENCES time_unit (id) ON DELETE CASCADE,
    organisms_density_id INTEGER REFERENCES organisms_density (id) ON DELETE CASCADE
);

-- intervention
CREATE TABLE intervention
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_type_id            INTEGER NOT NULL REFERENCES intervention_type (id) ON DELETE CASCADE,
    experiment_id                   INTEGER NOT NULL REFERENCES experiment (id) ON DELETE CASCADE,
    active_substance_id             INTEGER REFERENCES active_substance (id) ON DELETE CASCADE,
    dosage                          NUMERIC,
    dosage_unit_id                  INTEGER REFERENCES dosage_unit (id) ON DELETE CASCADE,
    treatment_group_id              INTEGER REFERENCES treatment_group (id) ON DELETE CASCADE,
    start_time                      NUMERIC,
    start_time_reference_point_id   INTEGER REFERENCES intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time                        NUMERIC,
    end_time_reference_point_id     INTEGER REFERENCES intervention_period_reference_point (id) ON DELETE CASCADE,
    substance_delivery_way_id       INTEGER REFERENCES substance_delivery_way (id) ON DELETE CASCADE,
    substance_delivery_frequency_id INTEGER REFERENCES substance_delivery_frequency (id) ON DELETE CASCADE,
    substance_delivery_method       TEXT
);

-- active_substance_drug_target
CREATE TABLE active_substance_drug_target
(
    active_substance_id INTEGER NOT NULL REFERENCES active_substance (id) ON DELETE CASCADE,
    drug_target_id      INTEGER NOT NULL REFERENCES drug_target (id)
);

-- active_substance_metabolic_enzyme
CREATE TABLE active_substance_metabolic_enzyme
(
    active_substance_id INTEGER NOT NULL REFERENCES active_substance (id) ON DELETE CASCADE,
    metabolic_enzyme_id INTEGER NOT NULL REFERENCES metabolic_enzyme (id)
);

-- active_substance_species
CREATE TABLE active_substance_species
(
    active_substance_id                INTEGER NOT NULL REFERENCES active_substance (id),
    species_id                         INTEGER NOT NULL REFERENCES species (id),
    half_life_time                     numrange,
    half_life_time_unit_id             INTEGER REFERENCES time_unit (id),
    half_life_time_elimination         numrange,
    half_life_time_elimination_unit_id INTEGER REFERENCES time_unit (id)
);
