"""
lsct_init
"""

from yoyo import step

__depends__ = {}

steps = [
    step('''

CREATE SCHEMA lsct;
ALTER
SCHEMA lsct OWNER TO admin;

CREATE TYPE lsct.diet_conditions AS
    (
    feed TEXT,
    times_per_day NUMERIC,
    feed_id INTEGER
    );

CREATE TYPE lsct.light_conditions AS
    (
    light_hours NUMERIC,
    dark_hours NUMERIC
    );

CREATE TYPE lsct.temperature_conditions AS
    (
    range numrange,
    constance boolean
    );

CREATE TABLE lsct.time_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE lsct.intervention_period_reference_point
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE lsct.intervention_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE lsct.journal
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    link TEXT,
    rank TEXT
);

CREATE TABLE lsct.metabolic_enzyme
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE lsct.species
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Name: sex; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.sex
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Name: nutrition; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.nutrition
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Name: organisms_density; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.organisms_density
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number    INTEGER NOT NULL,
    area      NUMERIC,
    area_unit TEXT,
    constancy boolean
);

-- Name: dosage_unit; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.dosage_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Name: drug_target; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.drug_target
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Name: experiment_site; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.experiment_site
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT
);

-- Name: strain; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.strain
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    species_id INTEGER NOT NULL REFERENCES lsct.species (id) ON DELETE CASCADE
);

CREATE TABLE lsct.control_group
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description               TEXT,
    control_min_lifespan      NUMERIC,
    control_max_lifespan      NUMERIC,
    control_median_lifespan   NUMERIC,
    lifespan_unit_id          INTEGER REFERENCES lsct.time_unit (id) ON DELETE CASCADE,
    organisms_density_id      INTEGER REFERENCES lsct.organisms_density (id) ON DELETE CASCADE,
    survival_plot_source_link TEXT,
    survival_plot_coordinates jsonb,
    survival_raw_data         jsonb
);

-- Name: publication; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.publication
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DOI"      TEXT,
    "PMID"     TEXT,
    date       date,
    journal_id INTEGER REFERENCES lsct.journal (id) ON DELETE CASCADE,
    authors    TEXT
);

-- Name: experiment; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.experiment
(
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          TEXT,
    publication_id                INTEGER NOT NULL REFERENCES lsct.publication (id) ON DELETE CASCADE,
    species_id                    INTEGER NOT NULL REFERENCES lsct.species (id) ON DELETE CASCADE,
    control_group_id              INTEGER REFERENCES lsct.control_group (id) ON DELETE CASCADE,
    strain_id                     INTEGER REFERENCES lsct.strain (id) ON DELETE CASCADE,
    experiment_site_id            INTEGER REFERENCES lsct.experiment_site (id) ON DELETE CASCADE,
    result_change_max_lifespan    NUMERIC,
    result_change_median_lifespan NUMERIC,
    sex_id                        INTEGER REFERENCES lsct.sex (id) ON DELETE CASCADE,
    temperature_conditions        lsct.temperature_conditions,
    light_conditions              lsct.light_conditions,
    diet_conditions               lsct.diet_conditions
);

-- Name: treatment_group; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.treatment_group
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size                 INTEGER NOT NULL,
    survival_plot_data   jsonb,
    min_lifespan         NUMERIC,
    mean_lifespan        NUMERIC,
    median_lifespan      NUMERIC,
    max_lifespan         NUMERIC,
    lifespan_unit_id     INTEGER REFERENCES lsct.time_unit (id) ON DELETE CASCADE,
    organisms_density_id INTEGER REFERENCES lsct.organisms_density (id) ON DELETE CASCADE
);

-- Name: intervention; Type: TABLE; Schema: lsct; Owner: admin
CREATE TABLE lsct.intervention
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_type_id            INTEGER NOT NULL REFERENCES lsct.intervention_type (id) ON DELETE CASCADE,
    experiment_id                   INTEGER NOT NULL REFERENCES lsct.experiment (id) ON DELETE CASCADE,
    active_substance_id             INTEGER,
    dosage                          NUMERIC,
    dosage_unit_id                  INTEGER,
    treatment_group_id              INTEGER REFERENCES lsct.treatment_group (id) ON DELETE CASCADE,
    start_time                      NUMERIC,
    start_time_reference_point_id   INTEGER REFERENCES lsct.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time_reference_point_id     INTEGER REFERENCES lsct.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time                        NUMERIC,
    substance_delivery_way_id       INTEGER,
    substance_delivery_frequency_id INTEGER,
    substance_delivery_method       TEXT
);

    ''',
         '''DROP SCHEMA lsct CASCADE;''')
]
