"""
lsct_init
"""

from yoyo import step

__depends__ = {}

steps = [
    step('''
-- DROP SCHEMA drinters CASCADE ;
-- drags_interventions

CREATE SCHEMA drinters;
ALTER SCHEMA drinters OWNER TO admin;

CREATE TABLE drinters.active_substance
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.substance_delivery_frequency
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.substance_delivery_way
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.dosage_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.drug_target
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.intervention_period_reference_point
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.intervention_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.metabolic_enzyme
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE drinters.organisms_density
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number    INTEGER NOT NULL,
    area      NUMERIC,
    area_unit TEXT,
    constancy boolean
);

CREATE TABLE drinters.publication
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DOI"      TEXT,
    "PMID"     TEXT,
    date       date,
    journal_id INTEGER REFERENCES lsct.journal (id) ON DELETE CASCADE,
    authors    TEXT
);



CREATE TABLE drinters.active_substance_drug_target
(
    active_substance_id INTEGER NOT NULL REFERENCES drinters.active_substance (id) ON DELETE CASCADE,
    drug_target_id      INTEGER NOT NULL REFERENCES drinters.drug_target (id)
);

CREATE TABLE drinters.active_substance_metabolic_enzyme
(
    active_substance_id INTEGER NOT NULL REFERENCES drinters.active_substance (id) ON DELETE CASCADE,
    metabolic_enzyme_id INTEGER NOT NULL REFERENCES drinters.metabolic_enzyme (id)
);

CREATE TABLE drinters.active_substance_species
(
    active_substance_id                  INTEGER NOT NULL REFERENCES drinters.active_substance (id),
    species_id                           INTEGER NOT NULL REFERENCES lsct.species (id),
    "half-life_time"                     numrange,
    "half-life_time_unit_id"             INTEGER REFERENCES lsct.time_unit (id),
    "half-life_time_elimination"         numrange,
    "half-life_time_elimination_unit_id" INTEGER REFERENCES lsct.time_unit (id)
);


CREATE TABLE drinters.experiment
(
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          TEXT,
    publication_id                INTEGER NOT NULL REFERENCES drinters.publication (id) ON DELETE CASCADE,
    species_id                    INTEGER NOT NULL REFERENCES lsct.species (id) ON DELETE CASCADE,
    control_group_id              INTEGER REFERENCES lsct.control_group (id) ON DELETE CASCADE,
    strain_id                     INTEGER REFERENCES lsct.strain (id) ON DELETE CASCADE,
    experiment_site_id            INTEGER REFERENCES lsct.experiment_site (id) ON DELETE CASCADE,
    result_change_max_lifespan    NUMERIC,
    result_change_median_lifespan NUMERIC,
    sex_id                        INTEGER REFERENCES lsct.sex (id) ON DELETE CASCADE,
    temperature_conditions        lsct.temperature_conditions,
    light_conditions              lsct.light_conditions,
    diet_conditions               lsct.diet_conditions
);

CREATE TABLE drinters.treatment_group
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size                 INTEGER NOT NULL,
    survival_plot_data   jsonb,
    min_lifespan         NUMERIC,
    mean_lifespan        NUMERIC,
    median_lifespan      NUMERIC,
    max_lifespan         NUMERIC,
    lifespan_unit_id     INTEGER REFERENCES lsct.time_unit (id) ON DELETE CASCADE,
    organisms_density_id INTEGER REFERENCES drinters.organisms_density (id) ON DELETE CASCADE
);

CREATE TABLE drinters.intervention
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_type_id            INTEGER NOT NULL REFERENCES drinters.intervention_type (id) ON DELETE CASCADE,
    experiment_id                   INTEGER NOT NULL REFERENCES drinters.experiment (id) ON DELETE CASCADE,
    active_substance_id             INTEGER REFERENCES drinters.active_substance (id) ON DELETE CASCADE,
    dosage                          NUMERIC,
    dosage_unit_id                  INTEGER REFERENCES drinters.dosage_unit (id) ON DELETE CASCADE,
    treatment_group_id              INTEGER REFERENCES drinters.treatment_group (id) ON DELETE CASCADE,
    start_time                      NUMERIC,
    start_time_reference_point_id   INTEGER REFERENCES drinters.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time_reference_point_id     INTEGER REFERENCES drinters.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time                        NUMERIC,
    substance_delivery_way_id       INTEGER REFERENCES drinters.substance_delivery_way (id) ON DELETE CASCADE,
    substance_delivery_frequency_id INTEGER REFERENCES drinters.substance_delivery_frequency (id) ON DELETE CASCADE,
    substance_delivery_method       TEXT
);

    ''',
         '''DROP SCHEMA drinters CASCADE;''')
]
