-- drags_interventions

CREATE SCHEMA interventions;
ALTER SCHEMA interventions OWNER TO admin;

CREATE TABLE interventions.active_substance
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.substance_delivery_frequency
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.substance_delivery_way
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.dosage_unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.drug_target
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.intervention_period_reference_point
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.intervention_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.metabolic_enzyme
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE interventions.organisms_density
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number    INTEGER NOT NULL,
    area      NUMERIC,
    area_unit TEXT,
    constancy boolean
);

CREATE TABLE interventions.publication
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DOI"      TEXT,
    "PMID"     TEXT,
    date       date,
    journal_id INTEGER REFERENCES listcontrols.journal (id) ON DELETE CASCADE,
    authors    TEXT
);

CREATE TABLE interventions.active_substance_drug_target
(
    active_substance_id INTEGER NOT NULL REFERENCES interventions.active_substance (id) ON DELETE CASCADE,
    drug_target_id      INTEGER NOT NULL REFERENCES interventions.drug_target (id)
);

CREATE TABLE interventions.active_substance_metabolic_enzyme
(
    active_substance_id INTEGER NOT NULL REFERENCES interventions.active_substance (id) ON DELETE CASCADE,
    metabolic_enzyme_id INTEGER NOT NULL REFERENCES interventions.metabolic_enzyme (id)
);

CREATE TABLE interventions.active_substance_species
(
    active_substance_id                  INTEGER NOT NULL REFERENCES interventions.active_substance (id),
    species_id                           INTEGER NOT NULL REFERENCES listcontrols.species (id),
    "half-life_time"                     numrange,
    "half-life_time_unit_id"             INTEGER REFERENCES listcontrols.time_unit (id),
    "half-life_time_elimination"         numrange,
    "half-life_time_elimination_unit_id" INTEGER REFERENCES listcontrols.time_unit (id)
);


CREATE TABLE interventions.experiment
(
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          TEXT,
    publication_id                INTEGER NOT NULL REFERENCES interventions.publication (id) ON DELETE CASCADE,
    species_id                    INTEGER NOT NULL REFERENCES listcontrols.species (id) ON DELETE CASCADE,
    control_group_id              INTEGER REFERENCES listcontrols.control_group (id) ON DELETE CASCADE,
    strain_id                     INTEGER REFERENCES listcontrols.strain (id) ON DELETE CASCADE,
    experiment_site_id            INTEGER REFERENCES listcontrols.experiment_site (id) ON DELETE CASCADE,
    result_change_max_lifespan    NUMERIC,
    result_change_median_lifespan NUMERIC,
    sex_id                        INTEGER REFERENCES listcontrols.sex (id) ON DELETE CASCADE,
    -- temperature_conditions
    temp_cond_range               numrange,
    temp_cond_constance           boolean,
    -- light_conditions
    light_cond_light_hours        NUMERIC,
    light_cond_dark_hours         NUMERIC,
    -- diet_condition
    diet_cond_feed_id             INTEGER,
    diet_cond_feed                TEXT,
    diet_cond_times_per_day       NUMERIC
);

CREATE TABLE interventions.treatment_group
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size                 INTEGER NOT NULL,
    survival_plot_data   jsonb,
    min_lifespan         NUMERIC,
    mean_lifespan        NUMERIC,
    median_lifespan      NUMERIC,
    max_lifespan         NUMERIC,
    lifespan_unit_id     INTEGER REFERENCES listcontrols.time_unit (id) ON DELETE CASCADE,
    organisms_density_id INTEGER REFERENCES interventions.organisms_density (id) ON DELETE CASCADE
);

CREATE TABLE interventions.intervention
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_type_id            INTEGER NOT NULL REFERENCES interventions.intervention_type (id) ON DELETE CASCADE,
    experiment_id                   INTEGER NOT NULL REFERENCES interventions.experiment (id) ON DELETE CASCADE,
    active_substance_id             INTEGER REFERENCES interventions.active_substance (id) ON DELETE CASCADE,
    dosage                          NUMERIC,
    dosage_unit_id                  INTEGER REFERENCES interventions.dosage_unit (id) ON DELETE CASCADE,
    treatment_group_id              INTEGER REFERENCES interventions.treatment_group (id) ON DELETE CASCADE,
    start_time                      NUMERIC,
    start_time_reference_point_id   INTEGER REFERENCES interventions.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time_reference_point_id     INTEGER REFERENCES interventions.intervention_period_reference_point (id) ON DELETE CASCADE,
    end_time                        NUMERIC,
    substance_delivery_way_id       INTEGER REFERENCES interventions.substance_delivery_way (id) ON DELETE CASCADE,
    substance_delivery_frequency_id INTEGER REFERENCES interventions.substance_delivery_frequency (id) ON DELETE CASCADE,
    substance_delivery_method       TEXT
);
